#
# idpd configuration
#

[logging]
# debug|info|warn|error
#level = "info"
# stdout|stderr|file|syslog
#target = "stdout"
# -1:auto-detect color output, 0:disable color output, 1:force color output (only applicable for targets stdout|stderr)
#color = -1
# <log file name> (only applicable for target file)
#file_name = "/var/log/idpd/idpd.log"
# 0:disable log file rotation, >0:rotate log file at this size (only applicable for target file)
#file_size_limit = 0
# tcp|udp
#syslog_network = "tcp"
# <syslog server address> (only applicable for target syslog)
#syslog_address = "localhost:601"
# rfc3164|rfc3164+framing|rfc5424|rfc5424+framing
#syslog_encoding = "rfc5424+framing"
# 0-23 (see https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.1)
#syslog_facility = 4

[server]
# listen address (host:port)
#address = "localhost:9123"
# http|https
#protocol = "http"
# enable access log generation
#access_log = false
# certificate file to use for https
#cert_file = ""
# key file to use for https
#key_file = ""
# public url to use, if running behind a reverse proxy
#public_url = ""
# session cookie name
#session_cookie = "idpd_session"
# session cookie lifetime = max age (in seconds)
#session_cookie_lifetime = "720h" # 30 days

[mail]
#address = "localhost:587"
#user = "idpd"
#password = ""
#from_address = "idpd@example.org"
#from_name = "IdPD"

[totp]
#issuer = ""

[geoip]
#city_db = "GeoLite2-City.mmdb"

[database]
# memory|sqlite|postgres
#type = "memory"

[database.memory]

[database.sqlite]
# SQLite db file
#file = "/var/lib/idpd/idpd.db"

[database.postgres]
# Postgres server address (host:port)
#address = "localhost:5432"
# Postgres database name
#db = "idpd"
# Postgres database user
#user = "idpd"
# Postgres database password
#password = ""

[userstore]
# static|ldap
#type = "static"

[userstore.ldap]
# LDAP server urls
#urls = [ "ldaps://dc.domain.example.org" ]
# LDAP bind dn
#bind_dn = "CN=idpd,CN=Users,DC=domain,DC=example,DC=org"
# LDAP bind password
#bind_password = ""
# LDAP user base DN
#user_base_dn = "CN=Users,DC=domain,DC=example,DC=org"
# LDAP user object filter
#user_filter = "(objectClass=user)"
# LDAP group base DN
#group_base_dn = "CN=Users,DC=domain,DC=example,DC=org"
# LDAP group object filter
#group_filter = "(objectClass=group)"
# active_directory | openldap | custom
#mapping = "active_directory"

[userstore.ldap.custom_mapping]
user.profile.name = "displayName"
user.profile.given_name = "givenName"
user.profile.family_name = "sn"
user.profile.middle_name = ""
user.profile.nickname = "initials"
user.profile.profile = ""
user.profile.picture = "jpegPhoto"
user.profile.website = ""
user.profile.birthdate = ""
user.profile.zoneinfo = ""
user.profile.locale = "preferredLanguage"
user.profile.preferred_username = "uid"
user.profile.update_at = "whenChanged"
user.address.formatted = "homePostalAddress"
user.address.street = "street"
user.address.locality = "l"
user.address.region = "st"
user.address.postal_code = "postalCode"
user.address.country = "c"
user.phone.number = "telephoneNumber"
user.email.address = "mail"
user.groups = ""
group.name = "cn"
group.members = "member"

#[[userstore.static]]
#subject = "subject"
#password = "password"
#groups = [ "group" ]
#[userstore.static.profile]
#name = "name"
#given_name = "given_name"
#family_name = "family_name"
#middle_name = "middle_name"
#nickname = "nickname"
#profile = "profile"
#picture = "picture"
#website = "website"
#birthdate = "birthdate"
#zoneinfo = "zoneinfo"
#locale = "locale"
#preferred_username = "preferred_username"
#[userstore.static.address]
#formatted = "formatted"
#street = "street"
#locality = "locality"
#region = "region"
#postal_code = "postal_code"
#country = "country"
#[userstore.static.phone]
#number = "number"
#[userstore.static.email]
#address = "address"

[oauth2]
#default_logout_redirect_url = ""
#signing_key_algorithm = "RS256"
#signing_key_lifetime = "1h"
#signing_key_expiry = "24h"

#[[oauth2.client]]
#id = "client 1"
#secret = "verysecretphrase"
#redirect_urls = [ "http://localhost:9124/authorized" ]
