#
# idpd configuration
#

# Logging
[logging]
# debug|info|warn|error
level = "info"
# stdout|stderr|file
target = "stdout"
# -1:disable color output, 0:auto-detect color output, 1:force color output (only applicable for targets stdout|stderr)
color = 1
# <log file name> (only applicable for target file)
file_name = "/var/log/idpd/idpd.log"
# 0:disable log file rotation, >0:rotate log file at this size (only applicable for target file)
file_size_limit = 0

# Server setup
[server]
address = "localhost:9123"
# http|https
protocol = "http"
cert_file = ""
key_file = ""
public_url = ""

# Database setup
[database]
type = "memory"

[database.memory]

[database.sqlite]
file = "/var/lib/idpd/idpd.db"

[database.postgres]
address = "localhost:5432"
db = "idpd"
user = "idpd"
password = "replace me"

# User store configuration
[userstore]
type = "static"

[userstore.ldap]
url = "ldap://localhost:1389"
bind_dn = "cn=idpd,dc=example,dc=org"
bind_password = "idpdpassword"
user_base_dn = "ou=users,dc=example,dc=org"
user_filter = "(&(objectClass=inetOrgPerson)(objectClass=posixAccount))"
group_base_dn = "ou=groups,dc=example,dc=org"
group_filter = "(objectClass=groupOfNames)"
# active_directory | openldap | custom
mapping = "active_directory"

[userstore.ldap.custom_mapping]
user.profile.name = "displayName"
user.profile.given_name = "givenName"
user.profile.family_name = "sn"
user.profile.middle_name = ""
user.profile.nickname = "initials"
user.profile.profile = ""
user.profile.picture = "jpegPhoto"
user.profile.website = ""
user.profile.birthdate = ""
user.profile.zoneinfo = ""
user.profile.locale = "preferredLanguage"
user.profile.preferred_username = "uid"
user.profile.update_at = "whenChanged"
user.address.formatted = "homePostalAddress"
user.address.street = "street"
user.address.locality = "l"
user.address.region = "st"
user.address.postal_code = "postalCode"
user.address.country = "c"
user.phone.number = "telephoneNumber"
user.email.address = "mail"
user.groups = ""
group.name = "cn"
group.members = "member"

#[[userstore.static.user]]
#subject = "subject"
#password = "password"
#groups = [ "group" ]
#[userstore.static.user.profile]
#name = "name"
#given_name = "given_name"
#family_name = "family_name"
#middle_name = "middle_name"
#nickname = "nickname"
#profile = "profile"
#picture = "picture"
#website = "website"
#birthdate = "birthdate"
#zoneinfo = "zoneinfo"
#locale = "locale"
#preferred_username = "preferred_username"
#[userstore.static.user.address]
#formatted = "formatted"
#street = "street"
#locality = "locality"
#region = "region"
#postal_code = "postal_code"
#country = "country"
#[userstore.static.user.phone]
#number = "number"
#[userstore.static.user.email]
#address = "address"

[openid]
allow_insecure = true
default_logout_redirect_url = "http://localhost:9123"
signing_key_algorithm = "RS256"
signing_key_lifetime = 3600 # 1h
signing_key_expiry = 86400 # 24h

# OpenID clients
#[[openid.client]]
#id = "client 1"
#secret = "verysecretphrase"
#redirect_urls = ["http://localhost:9123/authorized"]

#[[openid.client]]
#id = "client 2"
#secret = "veryverysecretphrase"
#redirect_urls = ["http://localhost:9123/authorized"]
