[logging]
level = "info"
target = "stdout"
color = -1
file_name = "/var/log/idpd/idpd.log"
file_size_limit = 0
syslog_network = "tcp"
syslog_address = "localhost:601"
syslog_encoding = "rfc5424"
syslog_facility = 4

[server]
address = "localhost:9123"
protocol = "http"
access_log = true
cert_file = ""
key_file = ""
public_url = ""
session_cookie = "idpd_session"
session_cookie_max_age = "720h"

[mail]
address = "localhost:587"
user = "idpd"
password = ""
from_address = "idpd@example.org"
from_name = "IdPD"

[geoip]
city_db = "GeoLite2-City.mmdb"

[database]
type = "memory"

[database.memory]

[database.sqlite]
file = "/var/lib/idpd/idpd.db"

[database.postgres]
address = "localhost:5432"
db = "idpd"
user = "idpd"
password = ""

[userstore]
type = "static"

[userstore.ldap]
urls = [ "ldaps://dc.domain.example.org" ]
bind_dn = "CN=idpd,CN=Users,DC=domain,DC=example,DC=org"
bind_password = ""
user_base_dn = "CN=Users,DC=domain,DC=example,DC=org"
user_filter = "(objectClass=user)"
group_base_dn = "CN=Users,DC=domain,DC=example,DC=org"
group_filter = "(objectClass=group)"
mapping = "active_directory"

[userstore.ldap.custom_mapping]
user.profile.name = "displayName"
user.profile.given_name = "givenName"
user.profile.family_name = "sn"
user.profile.middle_name = ""
user.profile.nickname = "initials"
user.profile.profile = ""
user.profile.picture = "jpegPhoto"
user.profile.website = ""
user.profile.birthdate = ""
user.profile.zoneinfo = ""
user.profile.locale = "preferredLanguage"
user.profile.preferred_username = "uid"
user.profile.update_at = "whenChanged"
user.address.formatted = "homePostalAddress"
user.address.street = "street"
user.address.locality = "l"
user.address.region = "st"
user.address.postal_code = "postalCode"
user.address.country = "c"
user.phone.number = "telephoneNumber"
user.email.address = "mail"
user.groups = ""
group.name = "cn"
group.members = "member"

#[[userstore.static]]
#subject = "subject"
#password = "password"
#groups = [ "group" ]
#[userstore.static.profile]
#name = "name"
#given_name = "given_name"
#family_name = "family_name"
#middle_name = "middle_name"
#nickname = "nickname"
#profile = "profile"
#picture = "picture"
#website = "website"
#birthdate = "birthdate"
#zoneinfo = "zoneinfo"
#locale = "locale"
#preferred_username = "preferred_username"
#[userstore.static.address]
#formatted = "formatted"
#street = "street"
#locality = "locality"
#region = "region"
#postal_code = "postal_code"
#country = "country"
#[userstore.static.phone]
#number = "number"
#[userstore.static.email]
#address = "address"

[oauth2]
default_logout_redirect_url = ""
signing_key_algorithm = "RS256"
signing_key_lifetime = "1h"
signing_key_expiry = "24h"

#[[oauth2.client]]
#id = "client 1"
#secret = "verysecretphrase"
#redirect_urls = ["http://localhost:9124/authorized"]
