[logging]
level = "info"
target = "stdout"
color = "auto"
file_name = "./idpd.log"
file_size_limit = 0
syslog_network = "tcp"
syslog_address = "localhost:601"
syslog_encoding = "rfc5424"
syslog_facility = 4

[server]
address = "localhost:0"
protocol = "http"
cert_file = ""
key_file = ""
public_url = ""
trusted_proxies = [ ]
trusted_headers = [ ]
allowed_origins = [ ]
access_log = ""
access_log_size_limit = 0

[store]
type = "memory"

[store.memory]

[store.sqlite]
file = "./idpd.db"

[store.postgres]
address = "localhost:5432"
db = "idpd"
user = "idpd"
password = ""

[general]
integrity_context_key_rotation = "720h"
integrity_context_key_lifetime = "1440h"

[oauth2]
enabled = true
claims = []
scopes = []
signing_key_algorithm = "RS256"
signing_key_rotation = "720h"
signing_key_lifetime = "1440h"
access_token_lifetime = "1h"
refresh_token_lifetime = "720h"
default_id_token_lifetime = "10m"

[saml2]
enabled = true
organization_name = ""
organization_url = ""
contact_email = ""

[forward]
enabled = true
