// Package rest Code generated by swaggo/swag. DO NOT EDIT
package rest

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/tdrn-org/idpd"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/info": {
            "get": {
                "description": "Retrieve basic server info like version and configured options",
                "produces": [
                    "application/json"
                ],
                "summary": "Query server info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ServerInfo"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "Ping the server to check general health",
                "produces": [
                    "text/plain"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/session": {
            "get": {
                "description": "Retrieve the current session information (if a session exists)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SessionInfo"
                        }
                    },
                    "404": {
                        "description": "no session found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Deletes the current session (if a session exists)",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete the current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SessionInfo"
                        }
                    },
                    "404": {
                        "description": "no session found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/session/login": {
            "get": {
                "description": "Retrieve the current session information (if a session exists)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SessionInfo"
                        }
                    },
                    "404": {
                        "description": "no session found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Initiate the authentication flow to create a new session",
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new session",
                "responses": {
                    "302": {
                        "description": "Redirect to Login UI",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/session/verify": {
            "get": {
                "description": "Retrieve the current session information (if a session exists)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SessionInfo"
                        }
                    },
                    "404": {
                        "description": "no session found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.ServerInfo": {
            "type": "object",
            "properties": {
                "version": {
                    "description": "The server version",
                    "type": "string"
                }
            }
        },
        "rest.SessionInfo": {
            "type": "object",
            "properties": {
                "strong_auth": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9123",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "IdPD REST API",
	Description:      "IdPD identity provider server API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
