basePath: /api
definitions:
  domain.Verification:
    enum:
    - email
    - totp
    - passkey
    - seckey
    type: string
    x-enum-varnames:
    - VerificationEmail
    - VerificationTOTP
    - VerificationPasskey
    - VerificationSecKey
  rest.ServerInfo:
    properties:
      base_url:
        description: The server's base URL
        type: string
      version:
        description: The server version
        type: string
    type: object
  rest.ServerInfoResponse:
    properties:
      code:
        $ref: '#/definitions/rest.StatusCode'
      data:
        $ref: '#/definitions/rest.ServerInfo'
      status:
        type: integer
      success:
        type: boolean
    type: object
  rest.SessionInfo:
    properties:
      strong_auth:
        type: boolean
      user:
        $ref: '#/definitions/rest.UserInfo'
    type: object
  rest.SessionInfoResponse:
    properties:
      code:
        $ref: '#/definitions/rest.StatusCode'
      data:
        $ref: '#/definitions/rest.SessionInfo'
      status:
        type: integer
      success:
        type: boolean
    type: object
  rest.SessionLoginInfo:
    properties:
      allowed_verifications:
        description: |-
          AllowedVerifications lists the allowed verification methods for this login flow.
          Only verification methods from this list are accepted during this login flow.
        items:
          $ref: '#/definitions/domain.Verification'
        type: array
      login_hint:
        description: |-
          LoginHint contains a hint for the login to use, if any can be derived from context.
          Can be overriden by the user.
        type: string
      remember:
        description: |-
          Remember indicates the default for whether to remember the login across browser sessions or not.
          Can be overriden by the user.
        type: boolean
    type: object
  rest.SessionLoginInfoResponse:
    properties:
      code:
        $ref: '#/definitions/rest.StatusCode'
      data:
        $ref: '#/definitions/rest.SessionLoginInfo'
      status:
        type: integer
      success:
        type: boolean
    type: object
  rest.SessionLoginRequest:
    properties:
      login:
        description: Login is the user login to use for the authentication
        type: string
      password:
        description: Password is the user password to use for the authentication
        type: string
      remember:
        description: Remember indicates whether to remember the given login across
          browser sessions or not.
        type: boolean
      verification:
        allOf:
        - $ref: '#/definitions/domain.Verification'
        description: Verification is the verification method to perform in the next
          step auf the authentication flow.
    type: object
  rest.SessionVerifyInfo:
    properties:
      verification:
        $ref: '#/definitions/domain.Verification'
    type: object
  rest.SessionVerifyInfoResponse:
    properties:
      code:
        $ref: '#/definitions/rest.StatusCode'
      data:
        $ref: '#/definitions/rest.SessionVerifyInfo'
      status:
        type: integer
      success:
        type: boolean
    type: object
  rest.SessionVerifyRequest:
    properties:
      response:
        description: Response is the response to the verification challenge
        type: string
    type: object
  rest.StatusCode:
    enum:
    - no_session
    - auth_request_not_accessible
    type: string
    x-enum-varnames:
    - StatusCodeNoSession
    - StatusCodeAuthRequestNotAccessible
  rest.StatusResponse:
    properties:
      code:
        $ref: '#/definitions/rest.StatusCode'
      status:
        type: integer
      success:
        type: boolean
    type: object
  rest.UserInfo:
    properties:
      email:
        type: string
      full_name:
        type: string
      groups:
        items:
          type: string
        type: array
      login:
        type: string
      picture:
        type: string
      short_name:
        type: string
    type: object
host: localhost:9123
info:
  contact:
    url: https://github.com/tdrn-org/idpd
  description: IdPD identity provider server API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: IdPD REST API
  version: "1.0"
paths:
  /api/info:
    get:
      description: Query static server info like version and configured options
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.ServerInfoResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Query server info
  /api/ping:
    get:
      description: Ping the server to check general health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Ping server
  /api/session:
    delete:
      description: Delete the current session (if a session exists)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete current session
    get:
      description: Get the current session (if a session exists)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.SessionInfoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rest.SessionInfoResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get current session
    post:
      description: Initiate the authentication flow to create a new session
      produces:
      - application/json
      responses:
        "302":
          description: Redirect to ...
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Initiate a new session
  /api/session/login/{id}:
    get:
      consumes:
      - application/json
      description: Get the login information for the authentication flow associated
        with the given authentication request
      parameters:
      - description: Authentication request ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.SessionLoginInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.SessionLoginInfoResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.SessionLoginInfoResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get login information
    post:
      consumes:
      - application/json
      description: Initiate the authentication flow to create a new session
      parameters:
      - description: Authentication request ID
        in: path
        name: id
        required: true
        type: string
      - description: Request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.SessionLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new session
  /api/session/verify/{id}:
    get:
      consumes:
      - application/json
      description: Get the verify information for the authentication flow associated
        with the given authentication request
      parameters:
      - description: Authentication request ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.SessionVerifyInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.SessionVerifyInfoResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get verify information
    post:
      consumes:
      - application/json
      description: Verify the authentication by providing the verification code
      parameters:
      - description: Authentication request ID
        in: path
        name: id
        required: true
        type: string
      - description: Request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.SessionVerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Verify authentication
swagger: "2.0"
