user.profile.name = "displayName"            #inetOrgPerson
user.profile.given_name = "givenName"        #inetOrgPerson
user.profile.family_name = "sn"              #inetOrgPerson
user.profile.middle_name = ""
user.profile.nickname = "initials"           #inetOrgPerson
user.profile.profile = ""
user.profile.picture = "jpegPhoto"           #inetOrgPerson
user.profile.website = ""
user.profile.birthdate = ""
user.profile.zoneinfo = ""
user.profile.locale = "preferredLanguage"    #inetOrgPerson
user.profile.preferred_username = "uid"      #inetOrgPerson
user.profile.update_at = "whenChanged"
user.address.formatted = "homePostalAddress" #inetOrgPerson
user.address.street = "street"               #inetOrgPerson
user.address.locality = "l"                  #inetOrgPerson
user.address.region = "st"                   #inetOrgPerson
user.address.postal_code = "postalCode"      #inetOrgPerson
user.address.country = "c"
user.phone.number = "telephoneNumber"        #inetOrgPerson
user.email.address = "mail"                  #inetOrgPerson
user.groups = ""
group.name = "cn"
group.members = "member"