user.profile.name = "displayName"
user.profile.given_name = "givenName"
user.profile.family_name = "sn"
user.profile.middle_name = ""
user.profile.nickname = ""
user.profile.profile = ""
user.profile.picture = ""
user.profile.website = ""
user.profile.birthdate = ""
user.profile.zoneinfo = ""
user.profile.locale = ""
user.profile.preferred_username = "sAMAccountName"
user.profile.update_at = "whenChanged"
user.address.formatted = ""
user.address.street = "street"
user.address.locality = "l"
user.address.region = ""
user.address.postal_code = "postalCode"
user.address.country = "c"
user.phone.number = "telephoneNumber"
user.email.address = "mail"
user.groups = ""
group.name = "sAMAccountName"
group.members = "member"